---
title: "Final Project"
output: pdf_document
authors: Leyla Akay and Maryann Zhao
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(message=FALSE, warning=FALSE, fig.height=3, fig.width=5, fig.align = "center")
library(dplyr)
library(ggplot2)
library(infer)
library(skimr)
library(broom)
library(mosaic)
library(knitr)
library(readr)
library(graphics)
library(GGally)
require(lattice)
library(readr)
library(purrr)
require(glmnet)
library(FactoMineR)
library(plot3D)
options(digits=3)
```

```{r}
movies <- read_csv("~/LM HW/SLM_Project/tmdb_2.csv")

#lang.table <- purrr::map(movies$spoken_languages, jsonlite::fromJSON)
#lang.table <- purrr::map_df(lang.table, ~data.frame(x=.x), .id="movieID")
#lang.table <- lang.table %>%
#  group_by(movieID) %>%
#  top_n(1, x.name)
#lang.table <- lang.table[3] %>% pull()
#movies <- movies %>%
#  mutate(lang=lang.table)

#original language english
lang <- c()
for (i in 1:4803){
 lang[i]<- ifelse(movies$original_language[i] == "en", 1, 0)
}
  
#dates after the year 2007
dates <- as.Date(movies$release_date, "%m/%d/%y")
dates <- as.numeric(substring(dates, 1, 4))
movies <- movies %>%
  mutate(years = dates) 
oh7 <- c()
for (i in 1:4803){
 oh7[i]<- ifelse(movies$years[i] >= 2007, 1, 0)
}


#check first 2 genres to see if they are action, adventure or drama based on most popular genres (website)
action <- c()
adv <- c()
drama <- c()
for (i in 1:4803){
 action[i] <- ifelse(movies$genres1[i] == "Action" | movies$genres2[i] == "Action", 1, 0)
 action[i] <- ifelse(is.nan(action[i]) | is.na(action[i]), 0, action[i])
 adv[i] <- ifelse(movies$genres1[i] == "Adventure" | movies$genres2[i] == "Adventure", 1, 0)
 adv[i] <- ifelse(is.nan(adv[i]) | is.na(adv[i]), 0, adv[i])
 drama[i] <- ifelse(movies$genres1[i] == "Drama" | movies$genres2[i] == "Drama", 1, 0)
 drama[i] <- ifelse(is.nan(drama[i]) | is.na(drama[i]), 0, drama[i])
}
movies <- movies %>%
  mutate(oh7 = oh7, action = action, adv = adv, drama = drama, lang = lang)



#Remove 0 values
movies.new <- movies %>%
  select(popularity, budget, revenue, vote_average, vote_count, oh7, adv, action, drama, lang) %>%
  filter(budget > 0, revenue > 0, vote_count > 0)

movies.log <- movies.new %>%
  mutate(pop.log = log(popularity), rev.log = log(revenue), bud.log = log(budget), count.log = log(vote_count), rev.bud.int = log(budget)*log(revenue))%>%
  select(pop.log, rev.log, vote_average, bud.log, count.log, oh7, adv, action, drama, lang, rev.bud.int)

#LM
og.lm <- lm(log(popularity) ~ log(revenue) + vote_average + log(budget), data=movies.new)
full.lm <- lm(log(popularity) ~ log(revenue) + vote_average + log(budget) + vote_count + oh7  + action + adv+ drama + lang , data=movies.new)
int.lm <- lm(log(popularity) ~ log(revenue) + vote_average + log(budget) + log(vote_count) + oh7 + adv + action + drama + lang + log(revenue)*log(budget), data=movies.new)

anova(og.lm, full.lm)
anova(full.lm, int.lm)
anova(int.lm)
anova(full.lm)
tidy(int.lm)

pop.budget <- lm(log(popularity) ~ log(vote_count), data = movies.new)
ggplot(pop.budget, aes(x=fitted(pop.budget), y=resid(pop.budget))) + geom_point()

set.seed(10)
lambda.grid =10^seq(5,-2, length =100)
movies.lasso.cv <- cv.glmnet(log(movies.new$revenue) + movies.new$vote_average + log(movies.new$budget) + movies.new$vote_count + movies.new$oh7 + movies.new$adv + movies.new$action + movies.new$drama + movies.new$lang + log(movies.new$revenue)*log(movies.new$budget), log(movies.new$population),alpha=1, lambda = lambda.grid, standardize=TRUE)

#LASSO 
sample <- sample.int(n = nrow(movies.log), size = floor(.90*nrow(movies.log)), replace = F)
train <- movies.log[sample, ]
test  <- movies.log[-sample, ]

movies.lasso.cv <- cv.glmnet(as.matrix(train[,2:11]), train$pop.log,alpha=1, lambda = lambda.grid, standardize=TRUE)
plot(movies.lasso.cv)+
  abline(v=log(movies.lasso.cv$lambda.min), col="green")
movies.lasso.cv$lambda.min
movies.lasso <- glmnet(as.matrix(train[,2:11]), train$pop.log,alpha=1, lambda = movies.lasso.cv$lambda.min, standardize=TRUE)
tidy(movies.lasso)

#plot lasso coefficients
colors <- rainbow(10)
movies.lasso <- glmnet(as.matrix(train[,2:11]), train$pop.log,alpha=1, lambda = lambda.grid, standardize=TRUE)
plot(movies.lasso, xvar="lambda", xlim=c(-6,10),col=colors)+
  abline(v=log(movies.lasso.cv$lambda.min))+
  abline(h=0, lty=2)+
  text(rep(-6.5, 10), coef(movies.lasso)[-1,length(lambda.grid)], colnames(train)[-1], pos=4, col=colors)
tidy(movies.lasso)

#ridge regression
movies.ridge.cv <- cv.glmnet(as.matrix(train[,2:11]), train$pop.log,alpha=0, lambda = lambda.grid, standardize=TRUE)
plot(movies.ridge.cv)+
  abline(v=log(movies.ridge.cv$lambda.min), col="green")
movies.ridge.cv$lambda.min
movies.ridge <- glmnet(as.matrix(train[,2:11]), train$pop.log,alpha=0, lambda = movies.ridge.cv$lambda.min, standardize=TRUE)
tidy(movies.ridge)


#plot RR coefficients
movies.ridge <- glmnet(as.matrix(train[,2:11]), train$pop.log,alpha=0, lambda = lambda.grid, standardize=TRUE)
plot(movies.ridge, xvar="lambda", xlim=c(-6,10),col=colors)+
  abline(v=log(movies.ridge.cv$lambda.min))+
  abline(h=0, lty=2)+
  text(rep(-6.5, 9), coef(movies.ridge)[-1,length(lambda.grid)], colnames(train)[-1], pos=4, col=colors)

ridge.pred <- predict(movies.ridge.cv, newx = as.matrix(test[,2:11]),
s = "lambda.min")
lasso.pred <- predict(movies.lasso.cv, newx = as.matrix(test[,2:11]),
s = "lambda.min")
mlr.pred <- predict(int.lm, newdata = data.frame(test.new[,2:10]), type = "response")

test.new<- test %>%
  mutate(popularity = pop.log, revenue = rev.log, budget = bud.log, vote_count = count.log)%>%
  select(popularity, revenue, vote_average, budget, vote_count, oh7, adv, action, drama, lang)

#regression splines
require(splines2)
count.knot6 <- bs(movies.log$count.log, df=6, degree=1)
count.rs <- lm(pop.log ~ count.knot, data=movies.log)
summary(count.rs)

#plot regression splines
qplot(count.log, pop.log, data=movies.log, geom=c("point", "smooth"), method = "lm", formula=y ~ ns(x, 6))
movies.log %>% ggplot(aes(count.log, pop.log)) + geom_point() + stat_smooth (method = "rlm")

#LOESS
count.lor <- loess(pop.log ~ count.log, span=.2, data=movies.log)

#PCA
movies.cont<- movies.log %>%
  select(rev.log, vote_average, bud.log, count.log)

pca <- prcomp(movies.cont, scale. = T, center = TRUE)

library(devtools)
#install_github("ggbiplot", "vqv")
 
library(ggbiplot)
g <- ggbiplot(pca, obs.scale = 1, var.scale = 1, groups = movies.cont$rev.log, ellipse = TRUE, 
              circle = TRUE)
g <- g + scale_color_discrete(name = '')
g <- g + theme(legend.direction = 'horizontal', 
               legend.position = 'top')
print(g)

pca <- PCA(movies.cont, graph = TRUE)
pca$eig

scatter3D(pca$eig[1], pca$eig[2], pca$eig[3], colvar = NULL, col = "blue",
          pch = 19, cex = 0.5)

pca <- prcomp(t(movies.cont), scale=TRUE)
fit <- hclust(dist(pca$x[,1:4]), method="complete") # 1:3 -> based on 3 components
groups <- cutree(fit, k=4)  
library(rgl)
plotPCA <- function(x, nGroup) {
    n <- ncol(x) 
    if(!(n %in% c(2,3))) { # check if 2d or 3d
        stop("x must have either 2 or 3 columns")
    }

    fit <- hclust(dist(x), method="complete") # cluster
    groups <- cutree(fit, k=nGroup)

    if(n == 3) { # 3d plot
        plot3D(x, col=groups, type="s", size=1, axes=F)
        axes3d(edges=c("x--", "y--", "z"), lwd=3, axes.len=2, labels=FALSE)
        grid3d("x")
        grid3d("y")
        grid3d("z")
    } else { # 2d plot
        maxes <- apply(abs(x), 2, max)
        rangeX <- c(-maxes[1], maxes[1])
        rangeY <- c(-maxes[2], maxes[2])
        plot(x, col=groups, pch=19, xlab=colnames(x)[1], ylab=colnames(x)[2], xlim=rangeX, ylim=rangeY)
        lines(c(0,0), rangeX*2)
        lines(rangeY*2, c(0,0))
    }
}
plotPCA(pca$x[,1:3], 4)

#logistic regression
library(caTools)
model <- glm (action ~ rev.log, data = movies.log, family = binomial)
summary(model)

ggplot(movies.log, aes(x=rev.log, y=action)) + geom_point() + 
stat_smooth(method="glm", family="binomial", se=FALSE)

fit = glm(action ~ rev.log, data=movies.log, family=binomial)
newdat <- data.frame(rev.log=seq(min(movies.log$rev.log), max(movies.log$rev.log)),len=100)
newdat$action = predict(fit, newdata=newdat, type="response")
plot(action ~ rev.log, data=movies.log, col="red4")
lines(action ~ rev.log, newdat, col="green4", lwd=2)

```

```{r}
#og model 
int.lm <- lm(log(popularity) ~ log(revenue) + vote_average + log(budget) + vote_count + oh7 + adv + action + drama + lang + log(revenue)*log(budget), data=movies.new)
tidy(int.lm)

#RR
movies.ridge <- glmnet(as.matrix(train[,2:11]), train$pop.log,alpha=0, lambda = movies.ridge.cv$lambda.min, standardize=TRUE)
tidy(movies.ridge)

#Lasso
movies.lasso <- glmnet(as.matrix(train[,2:11]), train$pop.log,alpha=1, lambda = movies.lasso.cv$lambda.min, standardize=TRUE)
tidy(movies.lasso)


ggplot(data = test, aes(x=pop.log, y=ridge.pred)) + 
  geom_point( colour = "yellow")  +
  geom_point(data = test, aes(x=pop.log, y=lasso.pred), colour="blue") +
  geom_point(data = test, aes(x=pop.log, y=mlr.pred), colour="green")+
  xlab ( "Observed Popularity")+
  ylab("Predicted Popularity") + 
  scale_shape_discrete(name  ="Model Type",
                          breaks=c("yellow", "blue", "green"),
                          labels=c("Ridge Regression", "Lasso", "MLR"))
  

```
```{r}
plot(test$pop.log, mlr.pred)
```




